export const PRODUCT_LABELS = {
  patientWorkspace: "Patient Portal",
  providerWorkspace: "Provider Portal",
  adminWorkspace: "Admin Portal",
  appointments: "Appointments",
  messages: "Messages",
  healthCheckins: "Health Check-ins",
  careHistory: "Care History",
  careSummaries: "Care Summaries",
  forms: "Forms",
  documents: "Documents",
  notifications: "Notifications",
  recipesAndResources: "Recipes & Resources",
  providerResponses: "Provider Responses",
} as const;

export const PROVIDER_SPECIALTY_TAXONOMY = [
  { slug: "primary-care", name: "Primary Care", category: "medical" },
  { slug: "family-medicine", name: "Family Medicine", category: "medical" },
  { slug: "pediatrics", name: "Pediatrics", category: "medical" },
  { slug: "gastroenterology", name: "Gastroenterology", category: "medical" },
  { slug: "cardiology", name: "Cardiology", category: "medical" },
  { slug: "endocrinology", name: "Endocrinology", category: "medical" },
  { slug: "neurology", name: "Neurology", category: "medical" },
  { slug: "psychiatry", name: "Psychiatry", category: "behavioral" },
  { slug: "therapy-counseling", name: "Therapy and Counseling", category: "behavioral" },
  { slug: "dietetics-nutrition", name: "Dietetics and Nutrition", category: "wellness" },
  { slug: "womens-health", name: "Women's Health", category: "medical" },
  { slug: "sleep-medicine", name: "Sleep Medicine", category: "medical" },
  { slug: "pain-management", name: "Pain Management", category: "medical" },
  { slug: "dermatology", name: "Dermatology", category: "medical" },
] as const;

export const CONDITION_FOCUS_TAXONOMY = [
  { slug: "ibs", name: "IBS", category: "digestive-health" },
  { slug: "gerd", name: "GERD", category: "digestive-health" },
  { slug: "crohns-disease", name: "Crohn's Disease", category: "digestive-health" },
  { slug: "ulcerative-colitis", name: "Ulcerative Colitis", category: "digestive-health" },
  { slug: "anxiety", name: "Anxiety", category: "mental-health" },
  { slug: "depression", name: "Depression", category: "mental-health" },
  { slug: "hypertension", name: "Hypertension", category: "cardiovascular" },
  { slug: "heart-health", name: "Heart Health", category: "cardiovascular" },
  { slug: "diabetes", name: "Diabetes", category: "metabolic-health" },
  { slug: "weight-management", name: "Weight Management", category: "metabolic-health" },
  { slug: "pcos", name: "PCOS", category: "womens-health" },
  { slug: "menopause-support", name: "Menopause Support", category: "womens-health" },
  { slug: "chronic-pain", name: "Chronic Pain", category: "pain-management" },
  { slug: "migraines", name: "Migraines", category: "neurology" },
  { slug: "insomnia", name: "Insomnia", category: "sleep-health" },
] as const;
